image: python:3

variables:
    DOCKER_DRIVER: overlay
    IMAGE_TAG: v1
test:
    stage: test
    image: python:3
    script:
        - ./tests.sh
build:
    stage: build
    image: docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
        - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG


